Configure now search for Python.h

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -11,8 +11,8 @@ Options:
       Displays this help message.
 
     --python=<version>
-      Specify a version of python to use. Possible values are:
-      python2.7, python3.5 and python3.5
+      Specify a version of python to use. Example:
+      --python=3.6m
 
     --no-tests
       Disable building of tests
@@ -38,22 +38,39 @@ static=0
 shared=0
 python="python2.7"
 pylib=""
+py_header=""
 
 check_python()
 {
-    if [ "$1" != "python2.7" -a "$1" != "python3.4" -a "$1" != "python3.5" ]; then
-        echo "Bad value for --python"
-        echo ""
-        helpmessage
-    fi
-    echo "Looking for python library path..."
-    pypath=`find /usr/lib/$1 -name "lib$1.so"`
-    if [ $? == 0 ]; then
-        echo $pylib
-        pylib=`dirname $pypath`
+    echo -n "Looking for libpython$1.so library path... "
+
+    pypath=`find /usr/lib -name "libpython$1.so"`
+    if [[ ( $? != 0 ) || ( -z "$pypath" ) ]]; then
+        echo "ERROR: Failed to find path to python library"
     else
-        echo "Failed to find path to python library"
+        pylib=`dirname $pypath`
+        echo "OK [$pylib]"
     fi
+}
+
+check_python_header() 
+{
+    echo -n "Looking for Python.h... "
+
+    local py_header_dir=`find /usr/include -name "python$1" -type d`
+    if [ $? != 0 ]; then
+        echo -e "FAIL"
+        echo -e "Couldn't find python$1 directory under /usr/include"
+        exit
+    fi
+    local py_header_path=`find $py_header_dir -name 'Python.h'`
+    if [ $? != 0 ]; then
+        echo -e "FAIL"
+        echo -e "Couldn't find Python.h in $py_header_dir"
+        exit
+    fi
+    py_header=`dirname $py_header_path`
+    echo -e "OK [$py_header]"
 }
 
 while [ $# -ge 1 ]; do
@@ -86,11 +103,14 @@ while [ $# -ge 1 ]; do
     shift
 done
 
+check_python_header $python
 check_python $python
 
 echo "# generated by configure script" > config.make
-echo "PYTHON_VER = $python" >> config.make
+# TODO: Remove hardcoded 'python' prefix
+echo "PYTHON_VER = python$python" >> config.make
 echo "PYLIB_DIR = $pylib" >> config.make
+echo "PYLIB_HEADER_DIR = $py_header" >> config.make
 if [ $shared -eq 0 ]; then
     if [ $static -eq 1 ]; then
         echo "STATIC_BUILD = 1" >> config.make
@@ -109,6 +129,7 @@ fi
 cat <<__EOF__ >>config.make
 export PYTHON_VER
 export PYLIB_DIR
+export PYLIB_HEADER_DIR
 export STATIC_BUILD
 export SHARED_BUILD
 export BUILD_TESTS
