Darwin build finished

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -45,8 +45,16 @@ py_header=""
 scheme="production"
 lib_ext=""
 openssl_dir=""
+# Top directory of openssl library
+openssl_directory=""
+# Operating system specific libraries used in library
 os_libs=""
-defines=
+# Additional defines added to CFLAGS
+extra_defines=
+# Additional libraries added to linker
+extra_libraries=
+# Code extension for Juce source files. On darwin we use 'mm'
+code_extension="cpp"
 
 os=$(uname)
 
@@ -56,17 +64,48 @@ if [ "$os" == "Linux" ]; then
     top_lib_dir=/usr/lib
     top_include_dir=/usr/include
     os_libs="-lrt"
-    defines="-DLINUX=1"
+    extra_defines="-DLINUX=1"
+    extra_libraries="-lX11 -lXext -lXinerama -lfreetype"
 elif [ "$os" == "Darwin" ]; then
     lib_ext="dylib"
     top_lib_dir=/usr/local
     top_include_dir=/usr/local
     s_libs=""
-    defines=
+    extra_defines=
+    code_extension="mm"
 else
     echo "$os unsupported platform"
     exit
 fi
+
+find_openssl_directory()
+{
+    echo -e "Looking for openssl directory..."
+
+    local header_location=`find $top_lib_dir -name 'crypto.h' | grep -v Permission`
+
+    if [[ ( $? != 0 ) || ( -z "$header_location" ) ]]; then
+        echo "ERROR: Failed to find path to python library"
+        exit
+    fi
+
+    while read -r line; do
+        while :
+        do
+            line=`dirname $line`
+            if [[ ( "$line" == "$top_lib_dir" ) || ( "$line" == "/" ) || ( $? != 0 ) ]]; then
+                break
+            fi
+            sslex=`find $line -name "libssl*$lib_ext" | grep -v Permission | head -1`
+            if [[ ( $? == 0 ) && ( ! -z "$sslex" ) ]]; then
+                openssl_directory=$line
+                echo -e "OK [$openssl_directory]"
+                return
+            fi
+        done
+    done <<< "$header_location"
+    echo "FAIL. openssl directory was not found"
+}
 
 check_python()
 {
@@ -100,7 +139,7 @@ check_python_header()
         py_header=`dirname $py_header_path`
         echo -e "OK [$py_header]"
         return
-    done <<< $py_header_dir
+    done <<< "$py_header_dir"
     echo -e "FAIL"
     echo -e "Couldn't find Python.h in:\n $py_header_dir"
     exit
@@ -157,19 +196,21 @@ done
 
 check_python_header $python
 check_python $python
-find_openssl_header
+#find_openssl_header
+find_openssl_directory
 
 echo "# generated by configure script" > config.make
-# TODO: Remove hardcoded 'python' prefix
 echo "PYTHON_VER = python$python" >> config.make
 echo "PYLIB_DIR = $pylib" >> config.make
 echo "PYLIB_HEADER_DIR = $py_header" >> config.make
 echo "BUILD_SCHEME = $scheme" >> config.make
-echo "OPENSSL_DIR = $openssl_dir" >> config.make
+echo "OPENSSL_DIR = $openssl_directory" >> config.make
 echo "OS = $os" >> config.make
 echo "SYSLIBS = $os_libs" >> config.make
 echo "LIB_EXT = $lib_ext" >> config.make
-echo "EXTRA_DEFINES = $defines" >> config.make
+echo "EXTRA_DEFINES = $extra_defines" >> config.make
+echo "CODE_EXT = $code_extension" >> config.make
+echo "EXTRA_LIBS = $extra_libraries" >> config.make
 if [ $shared -eq 0 ]; then
     if [ $static -eq 1 ]; then
         echo "STATIC_BUILD = 1" >> config.make
@@ -198,4 +239,6 @@ export OS
 export SYSLIBS
 export LIB_EXT
 export EXTRA_DEFINES
+export CODE_EXT
+export EXTRA_LIBS
 __EOF__
